// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f2b9DHN2DrvB6wFtHBQYGd
// Component: nVFFxfuVMWqXx

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  usePlasmicDataConfig,
  executePlasmicDataOp,
  usePlasmicDataOp
} from "@plasmicapp/react-web/lib/data-sources";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: zjTf886GGOJ0x/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_todo_mvc_app.module.css"; // plasmic-import: f2b9DHN2DrvB6wFtHBQYGd/projectcss
import sty from "./PlasmicTask.module.css"; // plasmic-import: nVFFxfuVMWqXx/css

export type PlasmicTask__VariantMembers = {
  state: "checked" | "editing";
};
export type PlasmicTask__VariantsArgs = {
  state?: SingleChoiceArg<"checked" | "editing">;
};
type VariantPropType = keyof PlasmicTask__VariantsArgs;
export const PlasmicTask__VariantProps = new Array<VariantPropType>("state");

export type PlasmicTask__ArgsType = {
  task?: any;
};
type ArgPropType = keyof PlasmicTask__ArgsType;
export const PlasmicTask__ArgProps = new Array<ArgPropType>("task");

export type PlasmicTask__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  text?: p.Flex<"div">;
  textbox?: p.Flex<"input">;
  button?: p.Flex<"button">;
};

export interface DefaultTaskProps {
  task?: any;
  state?: SingleChoiceArg<"checked" | "editing">;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTask__RenderFunc(props: {
  variants: PlasmicTask__VariantsArgs;
  args: PlasmicTask__ArgsType;
  overrides: PlasmicTask__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          task: { id: "fake-id", description: "Play with plasmic" }
        },
        props.args
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "state",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.state
      },
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $props.task.description;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries,
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const { cache, mutate: swrMutate } = usePlasmicDataConfig();
  const mutate = swrMutate;

  const globalVariants = ensureGlobalVariants({
    theme: useTheme()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootglobal_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [sty.rootglobal_theme_dark_state_editing]:
            hasVariant($state, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark"),
          [sty.rootstate_checked]: hasVariant($state, "state", "checked"),
          [sty.rootstate_editing]: hasVariant($state, "state", "editing")
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox___5XHlx, {
          [sty.freeBoxglobal_theme_dark_state_editing___5XHlxN2V9CVgn2K]:
            hasVariant($state, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark"),
          [sty.freeBoxstate_editing___5XHlxVgn2K]: hasVariant(
            $state,
            "state",
            "editing"
          )
        })}
      >
        {(hasVariant($state, "state", "editing") ? false : true) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__mJoOx, {
              [sty.freeBoxglobal_theme_dark_state_checked__mJoOxN2V9CWxWdL]:
                hasVariant($state, "state", "checked") &&
                hasVariant(globalVariants, "theme", "dark"),
              [sty.freeBoxstate_checked__mJoOxWxWdL]: hasVariant(
                $state,
                "state",
                "checked"
              ),
              [sty.freeBoxstate_editing__mJoOxVgn2K]: hasVariant(
                $state,
                "state",
                "editing"
              )
            })}
            onClick={async event => {
              const $steps = {};
              $steps["postgresUpdateMany"] = true
                ? (() => {
                    const actionArgs = {
                      dataOp: __wrapUserFunction(
                        {
                          type: "InteractionArgLoc",
                          actionName: "dataSourceOp",
                          interactionUuid: "ZQhh48ulDJvHP",
                          componentUuid: "nVFFxfuVMWqXx",
                          argName: "dataOp"
                        },
                        () => ({
                          sourceId: "jHy7mK2fQEcUDtkpExinyy",
                          opId: "88dfe826-89d1-4fa0-a489-d6a1e436f2bb",
                          userArgs: {
                            conditions: [$props.task.id],
                            variables: [!$props.task.done]
                          },
                          cacheKey: null,
                          invalidatedKeys: ["plasmic_refresh_all"],
                          roleId: null
                        })
                      )
                    };
                    return __wrapUserFunction(
                      {
                        type: "InteractionLoc",
                        actionName: "dataSourceOp",
                        interactionUuid: "ZQhh48ulDJvHP",
                        componentUuid: "nVFFxfuVMWqXx"
                      },
                      () =>
                        (async ({ dataOp, continueOnError }) => {
                          try {
                            const response = await executePlasmicDataOp(
                              dataOp,
                              {
                                userAuthToken: dataSourcesCtx?.userAuthToken,
                                user: dataSourcesCtx?.user
                              }
                            );
                            if (
                              dataOp.invalidatedKeys &&
                              dataOp.invalidatedKeys.find(
                                key => key === "plasmic_refresh_all"
                              )
                            ) {
                              await Promise.all(
                                Array.from(cache.keys()).map(async key =>
                                  mutate(key)
                                )
                              );
                              return response;
                            }
                            if (dataOp.invalidatedKeys) {
                              await Promise.all(
                                dataOp.invalidatedKeys.map(
                                  async invalidateKey =>
                                    Promise.all(
                                      Array.from(cache.keys()).map(
                                        async key => {
                                          if (
                                            typeof key === "string" &&
                                            key.includes(
                                              `.$.${invalidateKey}.$.`
                                            )
                                          ) {
                                            return mutate(key);
                                          }
                                          return Promise.resolve();
                                        }
                                      )
                                    )
                                )
                              );
                            }
                            return response;
                          } catch (e) {
                            if (!continueOnError) {
                              throw e;
                            }
                            return e;
                          }
                        })?.apply(null, [actionArgs]),
                      actionArgs
                    );
                  })()
                : undefined;
              if (
                typeof $steps["postgresUpdateMany"] === "object" &&
                typeof $steps["postgresUpdateMany"].then === "function"
              ) {
                $steps["postgresUpdateMany"] = await __wrapUserPromise(
                  {
                    type: "InteractionLoc",
                    actionName: "dataSourceOp",
                    interactionUuid: "ZQhh48ulDJvHP",
                    componentUuid: "nVFFxfuVMWqXx"
                  },
                  $steps["postgresUpdateMany"]
                );
              }
            }}
          >
            {(hasVariant($state, "state", "checked") ? true : false) ? (
              <p.PlasmicImg
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img, {
                  [sty.imgglobal_theme_dark_state_checked]:
                    hasVariant($state, "state", "checked") &&
                    hasVariant(globalVariants, "theme", "dark"),
                  [sty.imgstate_checked]: hasVariant(
                    $state,
                    "state",
                    "checked"
                  ),
                  [sty.imgstate_editing]: hasVariant($state, "state", "editing")
                })}
                displayHeight={
                  hasVariant($state, "state", "checked")
                    ? ("23px" as const)
                    : ("16px" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant($state, "state", "checked")
                    ? ("23px" as const)
                    : ("16px" as const)
                }
                src={
                  hasVariant($state, "state", "checked")
                    ? ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIiBzdHlsZT0iZmlsbDogcmdiKDQsIDE0MywgNjQpOyI+PHBhdGggZD0iTTE3My44OTggNDM5LjQwNGwtMTY2LjQtMTY2LjRjLTkuOTk3LTkuOTk3LTkuOTk3LTI2LjIwNiAwLTM2LjIwNGwzNi4yMDMtMzYuMjA0YzkuOTk3LTkuOTk4IDI2LjIwNy05Ljk5OCAzNi4yMDQgMEwxOTIgMzEyLjY5IDQzMi4wOTUgNzIuNTk2YzkuOTk3LTkuOTk3IDI2LjIwNy05Ljk5NyAzNi4yMDQgMGwzNi4yMDMgMzYuMjA0YzkuOTk3IDkuOTk3IDkuOTk3IDI2LjIwNiAwIDM2LjIwNGwtMjk0LjQgMjk0LjQwMWMtOS45OTggOS45OTctMjYuMjA3IDkuOTk3LTM2LjIwNC0uMDAxeiIvPjwvc3ZnPg==" as const)
                    : ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIj48cGF0aCBkPSJNMTczLjg5OCA0MzkuNDA0bC0xNjYuNC0xNjYuNGMtOS45OTctOS45OTctOS45OTctMjYuMjA2IDAtMzYuMjA0bDM2LjIwMy0zNi4yMDRjOS45OTctOS45OTggMjYuMjA3LTkuOTk4IDM2LjIwNCAwTDE5MiAzMTIuNjkgNDMyLjA5NSA3Mi41OTZjOS45OTctOS45OTcgMjYuMjA3LTkuOTk3IDM2LjIwNCAwbDM2LjIwMyAzNi4yMDRjOS45OTcgOS45OTcgOS45OTcgMjYuMjA2IDAgMzYuMjA0bC0yOTQuNCAyOTQuNDAxYy05Ljk5OCA5Ljk5Ny0yNi4yMDcgOS45OTctMzYuMjA0LS4wMDF6Ii8+PC9zdmc+" as const)
                }
              />
            ) : null}
          </div>
        ) : null}
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__v7Wr, {
          [sty.freeBoxglobal_theme_dark__v7WrN2V9C]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [sty.freeBoxglobal_theme_dark_state_editing__v7WrN2V9CVgn2K]:
            hasVariant($state, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark"),
          [sty.freeBoxstate_editing__v7WrVgn2K]: hasVariant(
            $state,
            "state",
            "editing"
          )
        })}
      >
        {(hasVariant($state, "state", "editing") ? false : true) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__jhTpD, {
              [sty.freeBoxstate_checked__jhTpDwxWdL]: hasVariant(
                $state,
                "state",
                "checked"
              ),
              [sty.freeBoxstate_editing__jhTpDvgn2K]: hasVariant(
                $state,
                "state",
                "editing"
              )
            })}
          >
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text,
                {
                  [sty.textstate_checked]: hasVariant(
                    $state,
                    "state",
                    "checked"
                  )
                }
              )}
              onDoubleClick={async event => {
                const $steps = {};
                $steps["updateState"] = true
                  ? (() => {
                      const actionArgs = {
                        vgroup: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariant",
                            interactionUuid: "lm7Xu4R4OC_9R",
                            componentUuid: "nVFFxfuVMWqXx",
                            argName: "vgroup"
                          },
                          () => "state"
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariant",
                            interactionUuid: "lm7Xu4R4OC_9R",
                            componentUuid: "nVFFxfuVMWqXx",
                            argName: "operation"
                          },
                          () => 0
                        ),
                        value: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariant",
                            interactionUuid: "lm7Xu4R4OC_9R",
                            componentUuid: "nVFFxfuVMWqXx",
                            argName: "value"
                          },
                          () => "editing"
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariant",
                          interactionUuid: "lm7Xu4R4OC_9R",
                          componentUuid: "nVFFxfuVMWqXx"
                        },
                        () =>
                          (({ vgroup, value }) => {
                            if (typeof value === "string") {
                              value = [value];
                            }

                            p.set($state, vgroup, value);
                            return value;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["updateState"] === "object" &&
                  typeof $steps["updateState"].then === "function"
                ) {
                  $steps["updateState"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariant",
                      interactionUuid: "lm7Xu4R4OC_9R",
                      componentUuid: "nVFFxfuVMWqXx"
                    },
                    $steps["updateState"]
                  );
                }
              }}
              onKeyDown={async event => {
                const $steps = {};
                $steps["tutorialdbUpdateMany"] = true
                  ? (() => {
                      const actionArgs = {
                        dataOp: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "dataSourceOp",
                            interactionUuid: "pcuciGqYXLiKa",
                            componentUuid: "nVFFxfuVMWqXx",
                            argName: "dataOp"
                          },
                          () => ({
                            sourceId: "jHy7mK2fQEcUDtkpExinyy",
                            opId: "3dd0c37f-9b8d-4b53-bdb9-68b199aaa675",
                            userArgs: {
                              conditions: [$props.task.id],
                              variables: [$state.textbox.value]
                            },
                            cacheKey: null,
                            invalidatedKeys: ["plasmic_refresh_all"],
                            roleId: null
                          })
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "dataSourceOp",
                          interactionUuid: "pcuciGqYXLiKa",
                          componentUuid: "nVFFxfuVMWqXx"
                        },
                        () =>
                          (async ({ dataOp, continueOnError }) => {
                            try {
                              const response = await executePlasmicDataOp(
                                dataOp,
                                {
                                  userAuthToken: dataSourcesCtx?.userAuthToken,
                                  user: dataSourcesCtx?.user
                                }
                              );
                              if (
                                dataOp.invalidatedKeys &&
                                dataOp.invalidatedKeys.find(
                                  key => key === "plasmic_refresh_all"
                                )
                              ) {
                                await Promise.all(
                                  Array.from(cache.keys()).map(async key =>
                                    mutate(key)
                                  )
                                );
                                return response;
                              }
                              if (dataOp.invalidatedKeys) {
                                await Promise.all(
                                  dataOp.invalidatedKeys.map(
                                    async invalidateKey =>
                                      Promise.all(
                                        Array.from(cache.keys()).map(
                                          async key => {
                                            if (
                                              typeof key === "string" &&
                                              key.includes(
                                                `.$.${invalidateKey}.$.`
                                              )
                                            ) {
                                              return mutate(key);
                                            }
                                            return Promise.resolve();
                                          }
                                        )
                                      )
                                  )
                                );
                              }
                              return response;
                            } catch (e) {
                              if (!continueOnError) {
                                throw e;
                              }
                              return e;
                            }
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["tutorialdbUpdateMany"] === "object" &&
                  typeof $steps["tutorialdbUpdateMany"].then === "function"
                ) {
                  $steps["tutorialdbUpdateMany"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "dataSourceOp",
                      interactionUuid: "pcuciGqYXLiKa",
                      componentUuid: "nVFFxfuVMWqXx"
                    },
                    $steps["tutorialdbUpdateMany"]
                  );
                }
              }}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.task.description;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "Enter some text";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
        ) : null}
        {(hasVariant($state, "state", "editing") ? true : false) ? (
          <input
            data-plasmic-name={"textbox"}
            data-plasmic-override={overrides.textbox}
            className={classNames(
              projectcss.all,
              projectcss.input,
              sty.textbox,
              {
                [sty.textboxglobal_theme_dark_state_editing]:
                  hasVariant($state, "state", "editing") &&
                  hasVariant(globalVariants, "theme", "dark"),
                [sty.textboxstate_editing]: hasVariant(
                  $state,
                  "state",
                  "editing"
                )
              }
            )}
            onBlur={async event => {
              const $steps = {};
              $steps["postgresUpdateMany"] = true
                ? (() => {
                    const actionArgs = {
                      dataOp: __wrapUserFunction(
                        {
                          type: "InteractionArgLoc",
                          actionName: "dataSourceOp",
                          interactionUuid: "AHkTBlZUBKBht",
                          componentUuid: "nVFFxfuVMWqXx",
                          argName: "dataOp"
                        },
                        () => ({
                          sourceId: "jHy7mK2fQEcUDtkpExinyy",
                          opId: "07def3fe-198e-45db-8c6e-41e21f40c484",
                          userArgs: {
                            variables: [$state.textbox.value],
                            conditions: [$props.task.id]
                          },
                          cacheKey: null,
                          invalidatedKeys: ["plasmic_refresh_all"],
                          roleId: null
                        })
                      )
                    };
                    return __wrapUserFunction(
                      {
                        type: "InteractionLoc",
                        actionName: "dataSourceOp",
                        interactionUuid: "AHkTBlZUBKBht",
                        componentUuid: "nVFFxfuVMWqXx"
                      },
                      () =>
                        (async ({ dataOp, continueOnError }) => {
                          try {
                            const response = await executePlasmicDataOp(
                              dataOp,
                              {
                                userAuthToken: dataSourcesCtx?.userAuthToken,
                                user: dataSourcesCtx?.user
                              }
                            );
                            if (
                              dataOp.invalidatedKeys &&
                              dataOp.invalidatedKeys.find(
                                key => key === "plasmic_refresh_all"
                              )
                            ) {
                              await Promise.all(
                                Array.from(cache.keys()).map(async key =>
                                  mutate(key)
                                )
                              );
                              return response;
                            }
                            if (dataOp.invalidatedKeys) {
                              await Promise.all(
                                dataOp.invalidatedKeys.map(
                                  async invalidateKey =>
                                    Promise.all(
                                      Array.from(cache.keys()).map(
                                        async key => {
                                          if (
                                            typeof key === "string" &&
                                            key.includes(
                                              `.$.${invalidateKey}.$.`
                                            )
                                          ) {
                                            return mutate(key);
                                          }
                                          return Promise.resolve();
                                        }
                                      )
                                    )
                                )
                              );
                            }
                            return response;
                          } catch (e) {
                            if (!continueOnError) {
                              throw e;
                            }
                            return e;
                          }
                        })?.apply(null, [actionArgs]),
                      actionArgs
                    );
                  })()
                : undefined;
              if (
                typeof $steps["postgresUpdateMany"] === "object" &&
                typeof $steps["postgresUpdateMany"].then === "function"
              ) {
                $steps["postgresUpdateMany"] = await __wrapUserPromise(
                  {
                    type: "InteractionLoc",
                    actionName: "dataSourceOp",
                    interactionUuid: "AHkTBlZUBKBht",
                    componentUuid: "nVFFxfuVMWqXx"
                  },
                  $steps["postgresUpdateMany"]
                );
              }
              $steps["updateState"] = true
                ? (() => {
                    const actionArgs = {
                      vgroup: __wrapUserFunction(
                        {
                          type: "InteractionArgLoc",
                          actionName: "updateVariant",
                          interactionUuid: "0lh898WdZC6Rs",
                          componentUuid: "nVFFxfuVMWqXx",
                          argName: "vgroup"
                        },
                        () => "state"
                      ),
                      operation: __wrapUserFunction(
                        {
                          type: "InteractionArgLoc",
                          actionName: "updateVariant",
                          interactionUuid: "0lh898WdZC6Rs",
                          componentUuid: "nVFFxfuVMWqXx",
                          argName: "operation"
                        },
                        () => 0
                      ),
                      value: __wrapUserFunction(
                        {
                          type: "InteractionArgLoc",
                          actionName: "updateVariant",
                          interactionUuid: "0lh898WdZC6Rs",
                          componentUuid: "nVFFxfuVMWqXx",
                          argName: "value"
                        },
                        () => []
                      )
                    };
                    return __wrapUserFunction(
                      {
                        type: "InteractionLoc",
                        actionName: "updateVariant",
                        interactionUuid: "0lh898WdZC6Rs",
                        componentUuid: "nVFFxfuVMWqXx"
                      },
                      () =>
                        (({ vgroup, value }) => {
                          if (typeof value === "string") {
                            value = [value];
                          }

                          p.set($state, vgroup, value);
                          return value;
                        })?.apply(null, [actionArgs]),
                      actionArgs
                    );
                  })()
                : undefined;
              if (
                typeof $steps["updateState"] === "object" &&
                typeof $steps["updateState"].then === "function"
              ) {
                $steps["updateState"] = await __wrapUserPromise(
                  {
                    type: "InteractionLoc",
                    actionName: "updateVariant",
                    interactionUuid: "0lh898WdZC6Rs",
                    componentUuid: "nVFFxfuVMWqXx"
                  },
                  $steps["updateState"]
                );
              }
            }}
            onChange={e => {
              p.generateStateOnChangeProp($state, ["textbox", "value"])(
                e.target.value
              );
            }}
            placeholder={"Enter task description" as const}
            ref={ref => {
              $refs["textbox"] = ref;
            }}
            type={"text" as const}
            value={p.generateStateValueProp($state, ["textbox", "value"]) ?? ""}
          />
        ) : null}
        {(hasVariant($state, "state", "editing") ? false : true) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__myvb, {
              [sty.freeBoxstate_editing__myvbvgn2K]: hasVariant(
                $state,
                "state",
                "editing"
              )
            })}
          >
            <button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames(
                projectcss.all,
                projectcss.button,
                projectcss.__wab_text,
                sty.button,
                {
                  [sty.buttonstate_editing]: hasVariant(
                    $state,
                    "state",
                    "editing"
                  )
                }
              )}
              onClick={async event => {
                const $steps = {};
                $steps["postgresDeleteMany"] = true
                  ? (() => {
                      const actionArgs = {
                        dataOp: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "dataSourceOp",
                            interactionUuid: "9YycATdXrjJRX",
                            componentUuid: "nVFFxfuVMWqXx",
                            argName: "dataOp"
                          },
                          () => ({
                            sourceId: "jHy7mK2fQEcUDtkpExinyy",
                            opId: "7ebc62a7-8bec-415d-af7b-73cda9e7fa90",
                            userArgs: {
                              conditions: [$props.task.id]
                            },
                            cacheKey: null,
                            invalidatedKeys: ["plasmic_refresh_all"],
                            roleId: null
                          })
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "dataSourceOp",
                          interactionUuid: "9YycATdXrjJRX",
                          componentUuid: "nVFFxfuVMWqXx"
                        },
                        () =>
                          (async ({ dataOp, continueOnError }) => {
                            try {
                              const response = await executePlasmicDataOp(
                                dataOp,
                                {
                                  userAuthToken: dataSourcesCtx?.userAuthToken,
                                  user: dataSourcesCtx?.user
                                }
                              );
                              if (
                                dataOp.invalidatedKeys &&
                                dataOp.invalidatedKeys.find(
                                  key => key === "plasmic_refresh_all"
                                )
                              ) {
                                await Promise.all(
                                  Array.from(cache.keys()).map(async key =>
                                    mutate(key)
                                  )
                                );
                                return response;
                              }
                              if (dataOp.invalidatedKeys) {
                                await Promise.all(
                                  dataOp.invalidatedKeys.map(
                                    async invalidateKey =>
                                      Promise.all(
                                        Array.from(cache.keys()).map(
                                          async key => {
                                            if (
                                              typeof key === "string" &&
                                              key.includes(
                                                `.$.${invalidateKey}.$.`
                                              )
                                            ) {
                                              return mutate(key);
                                            }
                                            return Promise.resolve();
                                          }
                                        )
                                      )
                                  )
                                );
                              }
                              return response;
                            } catch (e) {
                              if (!continueOnError) {
                                throw e;
                              }
                              return e;
                            }
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["postgresDeleteMany"] === "object" &&
                  typeof $steps["postgresDeleteMany"].then === "function"
                ) {
                  $steps["postgresDeleteMany"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "dataSourceOp",
                      interactionUuid: "9YycATdXrjJRX",
                      componentUuid: "nVFFxfuVMWqXx"
                    },
                    $steps["postgresDeleteMany"]
                  );
                }
              }}
            >
              {"\u00d7"}
            </button>
          </div>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "text", "textbox", "button"],
  img: ["img"],
  text: ["text"],
  textbox: ["textbox"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
  text: "div";
  textbox: "input";
  button: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTask__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTask__VariantsArgs;
    args?: PlasmicTask__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTask__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTask__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTask__ArgProps,
          internalVariantPropNames: PlasmicTask__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTask__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTask";
  } else {
    func.displayName = `PlasmicTask.${nodeName}`;
  }
  return func;
}

export const PlasmicTask = Object.assign(
  // Top-level PlasmicTask renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),
    textbox: makeNodeComponent("textbox"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicTask
    internalVariantProps: PlasmicTask__VariantProps,
    internalArgProps: PlasmicTask__ArgProps
  }
);

export default PlasmicTask;
/* prettier-ignore-end */
