// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f2b9DHN2DrvB6wFtHBQYGd
// Component: l4JHRTTG9DTqF

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  usePlasmicDataConfig,
  executePlasmicDataOp,
  usePlasmicDataOp
} from "@plasmicapp/react-web/lib/data-sources";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: zjTf886GGOJ0x/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_todo_mvc_app.module.css"; // plasmic-import: f2b9DHN2DrvB6wFtHBQYGd/projectcss
import sty from "./PlasmicHeader.module.css"; // plasmic-import: l4JHRTTG9DTqF/css

export type PlasmicHeader__VariantMembers = {
  state: "empty" | "allChecked";
};
export type PlasmicHeader__VariantsArgs = {
  state?: SingleChoiceArg<"empty" | "allChecked">;
};
type VariantPropType = keyof PlasmicHeader__VariantsArgs;
export const PlasmicHeader__VariantProps = new Array<VariantPropType>("state");

export type PlasmicHeader__ArgsType = {};
type ArgPropType = keyof PlasmicHeader__ArgsType;
export const PlasmicHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicHeader__OverridesType = {
  headerContainer?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  textbox?: p.Flex<"input">;
};

export interface DefaultHeaderProps {
  state?: SingleChoiceArg<"empty" | "allChecked">;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHeader__RenderFunc(props: {
  variants: PlasmicHeader__VariantsArgs;
  args: PlasmicHeader__ArgsType;
  overrides: PlasmicHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "state",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.state
      },
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          hasVariant(globalVariants, "theme", "dark")
            ? ("My Task" as const)
            : undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries,
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const { cache, mutate: swrMutate } = usePlasmicDataConfig();
  const mutate = swrMutate;

  const globalVariants = ensureGlobalVariants({
    theme: useTheme()
  });

  return (
    <div
      data-plasmic-name={"headerContainer"}
      data-plasmic-override={overrides.headerContainer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.headerContainer,
        {
          [sty.headerContainerglobal_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [sty.headerContainerstate_allChecked]: hasVariant(
            $state,
            "state",
            "allChecked"
          ),
          [sty.headerContainerstate_empty]: hasVariant($state, "state", "empty")
        }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxstate_empty]: hasVariant($state, "state", "empty")
        })}
      >
        {(hasVariant($state, "state", "empty") ? false : true) ? (
          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img, {
              [sty.imgglobal_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              ),
              [sty.imgstate_allChecked]: hasVariant(
                $state,
                "state",
                "allChecked"
              ),
              [sty.imgstate_empty]: hasVariant($state, "state", "empty")
            })}
            displayHeight={"30px" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"none" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"30px" as const}
            src={
              hasVariant(globalVariants, "theme", "dark")
                ? ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAxMiA2IiBoZWlnaHQ9IjYiIHdpZHRoPSIxMiIgc3R5bGU9ImZpbGw6IHJnYigyMTMsIDIwNiwgMjA2KTsiPgo8cGF0aCBmaWxsPSJibGFjayIgZD0iTTAuNjEyIDAuMTEyTDUuODQ0IDMuMjJMMTEuMDc2IDAuMTEyVjIuNUw1Ljg0NCA1LjUyNEwwLjYxMiAyLjQ4OFYwLjExMloiLz4KPC9zdmc+" as const)
                : ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAxMiA2IiBoZWlnaHQ9IjYiIHdpZHRoPSIxMiI+CjxwYXRoIGZpbGw9ImJsYWNrIiBkPSJNMC42MTIgMC4xMTJMNS44NDQgMy4yMkwxMS4wNzYgMC4xMTJWMi41TDUuODQ0IDUuNTI0TDAuNjEyIDIuNDg4VjAuMTEyWiIvPgo8L3N2Zz4K" as const)
            }
          />
        ) : null}
      </div>
      <input
        data-plasmic-name={"textbox"}
        data-plasmic-override={overrides.textbox}
        className={classNames(projectcss.all, projectcss.input, sty.textbox, {
          [sty.textboxglobal_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [sty.textboxstate_allChecked]: hasVariant(
            $state,
            "state",
            "allChecked"
          ),
          [sty.textboxstate_empty]: hasVariant($state, "state", "empty")
        })}
        onChange={e => {
          p.generateStateOnChangeProp($state, ["textbox", "value"])(
            e.target.value
          );
        }}
        onKeyDown={async event => {
          const $steps = {};
          $steps["postgresCreate"] =
            event.key === "Enter"
              ? (() => {
                  const actionArgs = {
                    dataOp: __wrapUserFunction(
                      {
                        type: "InteractionArgLoc",
                        actionName: "dataSourceOp",
                        interactionUuid: "r1QlUs_Sztf7A",
                        componentUuid: "l4JHRTTG9DTqF",
                        argName: "dataOp"
                      },
                      () => ({
                        sourceId: "jHy7mK2fQEcUDtkpExinyy",
                        opId: "f3bda36a-17f2-46f5-a510-7f982d17ff2e",
                        userArgs: {
                          variables: [$state.textbox.value]
                        },
                        cacheKey: null,
                        invalidatedKeys: ["plasmic_refresh_all"],
                        roleId: null
                      })
                    )
                  };
                  return __wrapUserFunction(
                    {
                      type: "InteractionLoc",
                      actionName: "dataSourceOp",
                      interactionUuid: "r1QlUs_Sztf7A",
                      componentUuid: "l4JHRTTG9DTqF"
                    },
                    () =>
                      (async ({ dataOp, continueOnError }) => {
                        try {
                          const response = await executePlasmicDataOp(dataOp, {
                            userAuthToken: dataSourcesCtx?.userAuthToken,
                            user: dataSourcesCtx?.user
                          });
                          if (
                            dataOp.invalidatedKeys &&
                            dataOp.invalidatedKeys.find(
                              key => key === "plasmic_refresh_all"
                            )
                          ) {
                            await Promise.all(
                              Array.from(cache.keys()).map(async key =>
                                mutate(key)
                              )
                            );
                            return response;
                          }
                          if (dataOp.invalidatedKeys) {
                            await Promise.all(
                              dataOp.invalidatedKeys.map(async invalidateKey =>
                                Promise.all(
                                  Array.from(cache.keys()).map(async key => {
                                    if (
                                      typeof key === "string" &&
                                      key.includes(`.$.${invalidateKey}.$.`)
                                    ) {
                                      return mutate(key);
                                    }
                                    return Promise.resolve();
                                  })
                                )
                              )
                            );
                          }
                          return response;
                        } catch (e) {
                          if (!continueOnError) {
                            throw e;
                          }
                          return e;
                        }
                      })?.apply(null, [actionArgs]),
                    actionArgs
                  );
                })()
              : undefined;
          if (
            typeof $steps["postgresCreate"] === "object" &&
            typeof $steps["postgresCreate"].then === "function"
          ) {
            $steps["postgresCreate"] = await __wrapUserPromise(
              {
                type: "InteractionLoc",
                actionName: "dataSourceOp",
                interactionUuid: "r1QlUs_Sztf7A",
                componentUuid: "l4JHRTTG9DTqF"
              },
              $steps["postgresCreate"]
            );
          }
          $steps["updateTextboxValue"] =
            event.key === "Enter"
              ? (() => {
                  const actionArgs = {
                    variable: __wrapUserFunction(
                      {
                        type: "InteractionArgLoc",
                        actionName: "updateVariable",
                        interactionUuid: "LnsLKyhYvZWm6",
                        componentUuid: "l4JHRTTG9DTqF",
                        argName: "variable"
                      },
                      () => ({
                        objRoot: $state,
                        variablePath: ["textbox", "value"]
                      })
                    ),
                    operation: __wrapUserFunction(
                      {
                        type: "InteractionArgLoc",
                        actionName: "updateVariable",
                        interactionUuid: "LnsLKyhYvZWm6",
                        componentUuid: "l4JHRTTG9DTqF",
                        argName: "operation"
                      },
                      () => 1
                    )
                  };
                  return __wrapUserFunction(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "LnsLKyhYvZWm6",
                      componentUuid: "l4JHRTTG9DTqF"
                    },
                    () =>
                      (({ variable, value, startIndex, deleteCount }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        p.set(objRoot, variablePath, undefined);
                        return undefined;
                      })?.apply(null, [actionArgs]),
                    actionArgs
                  );
                })()
              : undefined;
          if (
            typeof $steps["updateTextboxValue"] === "object" &&
            typeof $steps["updateTextboxValue"].then === "function"
          ) {
            $steps["updateTextboxValue"] = await __wrapUserPromise(
              {
                type: "InteractionLoc",
                actionName: "updateVariable",
                interactionUuid: "LnsLKyhYvZWm6",
                componentUuid: "l4JHRTTG9DTqF"
              },
              $steps["updateTextboxValue"]
            );
          }
        }}
        placeholder={"What needs to be done?" as const}
        ref={ref => {
          $refs["textbox"] = ref;
        }}
        type={"text" as const}
        value={p.generateStateValueProp($state, ["textbox", "value"]) ?? ""}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  headerContainer: ["headerContainer", "freeBox", "img", "textbox"],
  freeBox: ["freeBox", "img"],
  img: ["img"],
  textbox: ["textbox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  headerContainer: "div";
  freeBox: "div";
  img: typeof p.PlasmicImg;
  textbox: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeader__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHeader__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHeader__ArgProps,
          internalVariantPropNames: PlasmicHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "headerContainer") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("headerContainer"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    img: makeNodeComponent("img"),
    textbox: makeNodeComponent("textbox"),

    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
